### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mayeaux** [RedRiverSoftware/rr-guerrillamail#4]
Doesn't seem to be any. Is this actively maintained?

**Comment by kierenj** [comment]
It was shared and working, in case anyone would benefit from use. Happy to give guidance and support if you have any issues!

**Comment by kierenj** [comment]
(Have just copied a quick example into the readme - hope that helps.)

**Comment by mayeaux** [comment]
Okay cool thanks 👍
